apiVersion: v1
kind: Secret
metadata:
  name: smart-garage-secrets
type: Opaque
stringData: 
  GEMINI_API_KEY: "AIzaSyDyw_aDRAPX99kX-DAxMCHxqqW9V12Dq6M"
  MAINTENANCE_API_KEY: "my-super-secret-password"
  JWT_SECRET: "super-secret-jwt-token-123"